language: cpp

branches:
  only:
  - staging
  - trying
  - master
  # release branch
  - /^release\/[\d\.]+$/
  # release tag
  - /^v[\d\.]+$/

before_install: &decrypt-bot-data
- openssl aes-256-cbc -K $encrypted_93b6eceb9e8b_key -iv $encrypted_93b6eceb9e8b_iv
  -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
- tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}
script:
- gpg --list-keys
- gpg --list-secret-key
- gpg --detach-sign $HOME/.ssh/known_hosts
